name: PrizePicks Tracker
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # We are now using curl_cffi for the 403 bypass
          pip install curl_cffi discord-webhook

 - name: Run Script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SCRAPE_DO_TOKEN: ${{ secrets.SCRAPE_DO_TOKEN }}
        run: python main.py
